### PR TITLE
Improved error response handling. Closes #49

### LINKED ISSUE #49: Feature request: more meaningful error codes and information when a request fails
We have a finicky client server to work with that frequently returns a 404 not found. However, when using the API there's no way to report or log this, because any and all invalid response errors just seem to have code 11 (for empty response) and no information at all from the response itself.

The Response object provided by the Httpful library contains everything that's needed, it's just not being used in a helpful way. The _finishResponse method simply throws an InvalidResponseException with the return value of the _isValidResponse method along with the parsed out URL. It would be a lot more helpful if that exception message at least contained the response code from the request. To that end, the _finishResponse method should have the $buffer variable passed into it directly to allow for more robust response validation. That way _isValidResponse could be sent the full response object in order to do more robust response validation, returning the appropriate information in case it is invalid. This could then be used when throwing the exception in the _finishResponse method.

### PR DESCRIPTION
**Pull request by theteknocat**
### Summary

As per issue #49, if the Matomo server responds with an error code other than 200 that is not handled by an Httpful NetworkErrorException (which this library is already catching and handling accordingly), then it's very hard to get a meaningful error that can be used for troubleshooting.

If the server being queried is perhaps finicky for some reason and sometimes returns unexpected erroneous responses, such as 403, or 404 etc, there needs to be a way to see that for troubleshooting purposes.

This pull request, therefore, changes how server responses are validated and parsed so that more meaningful error messages can be provided through exceptions.

To that end, the _isValidResponse method has been updated to take the full Httpful\Response object as it's first argument so it can properly inspect it for unexpected invalid response codes and act accordingly. If a response code other than 200 was sent back, it will throw an InvalidResponseException with the details of that error. If it does have a 200 response, then it will check to see if the response body is empty and throw an exception using the ERROR_EMPTY code.

The _parseResponse method is now responsible for calling the _isValidResponse method, but does not catch any exceptions - it just allows exceptions to bubble up to be handled by the _finishResponse method. If no exceptions are thrown, it does it's parsing job as before and returns the appropriate response data per the specified format parameter.

The _finishResponse method calls for parsing of the response using a try/catch, so if there's no problem it returns the parsed response as it always did. It does include a double check to see if the parsed response is null, which should never happen but is there just in case of some weird issue that can't be foreseen at this time. If an InvalidResponseException is caught, it compiles the information into something helpful using the information from the originally thrown exception and re-throws it so that the _response method will catch and re-throw it as an InvalidRequestException as it always has.

The end result is more informative info in the exception message, which works perfectly in my case where a VPN (or internal network) connection is require to access the Matomo server, otherwise you get a 404 response. However, even if you are connected to the VPN, it can sometimes have other connectivity issues that may result in the same, or different status codes from the server.

I would appreciate a thorough review and testing of this code to ensure that it works in other use cases and that the code meets desired standards.

### CODE REVIEW

**Comment by thelfensdrfer** [comment]
Looks good so far, haven't had time to check it out yet in detail but will merge it by the end of the week (most likely Saturday/Sunday)!

**Comment by thelfensdrfer** [comment]
Whoops, it auto closed the pr because I renamed the main branch. But anyways, sorry for your trouble but I saw that some parts of the code, especially the request sending stuff was not optimal at all.

I refactored everything a little bit and released version 1.7.0. I am now pretty sure that the error stuff you mentioned was already in there but now it is for sure. There were already some tests in place, i refactored them so you can see how you get the error code, e.g. for 403 / 404 status codes. The problem here is that matomo does not always send the correct status code. For example, when you send an invalid auth token, the status code is still 200 but with an error message. Feel free to add additional features but please also make sure to write a new test for them.

Thanks again for your work and if you have any other questions or comments, please go ahead :)

**Comment by theteknocat** [comment]
No worries, thanks for sorting it out! I suspect I may have written my code against and older version in the end, as something I didn't realise until today is that I was stuck on v1.5 and at the moment cannot upgrade to 1.7 in my project.

Version 1.7 of this module depends on voku/httpful, which depends on psr/log v 1.1 and my project (Laravel, currently v10) requires psr/log 2 or 3 because it's using monolog. There's an issue for that on voku/httpful opened 2 weeks ago but I'm not sure when that'll get resolved. So I'm not sure what to do in the short term because I've started getting another error in 1.5 that you probably fixed in 1.7. It happens when fetching a goal where the _parseUrl method can't handle one of the params being an array instead of a string (the columns param).

For the short term it looks like I'll have to figure out some way of patching it until there's a new release of voku/httpful, unless of course a different http client library could be used instead of that one. But I'm guessing there's a reason you chose that one over say something like Guzzle http.

The joys of working with open source projects. I suppose another option for me would be to downgrade back to Laravel 9 and php 8.0 which seemed to have no problem, but I hate to take a step backwards.

**Comment by theteknocat** [comment]
@thelfensdrfer if I can find some time for it I'd be happy to do that. Seems like it would be a good update to do. Ideally I'd do it on work time with clients' budget, but that's not an option at the moment. I've reverted back to Laravel 9 in the short term (on which I can use v1.7 of this library no problem) so I can get on with the billable work and am watching this issue as well: https://github.com/voku/httpful/issues/14.

**Comment by thelfensdrfer** [comment]
Sounds good, no hurry.

**Pull request closed without merging**
